// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppFooter from "./home/Footer";
import NavBar from "./home/NavBar";
// Load Geist fonts
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
    suppressHydrationWarning
    className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
  >
    <NavBar />
    <main className="flex-1">{children}</main>
    <AppFooter />
  </body>
    </html>
  );
}
